services:
  mysql:
    image: "mysql:latest"
    container_name: "mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "local"

  zookeeper:
    image: "confluentinc/cp-zookeeper:latest"
    container_name: "zookeeper"
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: "2181"

  kafka:
    image: "confluentinc/cp-kafka:latest"
    container_name: "kafka"
    depends_on:
      - "zookeeper"
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    command:
      - bash
      - -c
      - |
        /etc/confluent/docker/run &
        sleep 30
        kafka-topics --create --topic audit_log --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1
        wait

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.14.0"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"

  kibana:
    image: "docker.elastic.co/kibana/kibana:7.14.0"
    depends_on:
      - "elasticsearch"
    ports:
      - "5601:5601"

  logstash:
    image: "docker.elastic.co/logstash/logstash:7.14.0"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
      - kafka
